/*
10. Revenue by Generation
For each hotel, calculate total revenue generated by:
- Millennials (born between 1980 and 1996)
- Gen Z (born after 1996)
*/

SELECT 
    hb.hotel_id,
    SUM(
        CASE 
            WHEN TO_DATE(c.dob, 'DD-MM-YY') 
                 BETWEEN '1980-01-01' AND '1996-12-31'
            THEN hb.number_of_nights * hb.per_night_rate
        END
    ) AS millennials_revenue,
    SUM(
        CASE 
            WHEN TO_DATE(c.dob, 'DD-MM-YY') >= '1997-01-01'
            THEN hb.number_of_nights * hb.per_night_rate
        END
    ) AS genz_revenue
FROM hotel_bookings hb
JOIN customers c ON hb.customer_id = c.customer_id
GROUP BY hb.hotel_id
ORDER BY hb.hotel_id;



/*
11. Average Stay Duration
Find the average stay duration (in nights) for each hotel.
*/

SELECT 
    hotel_id,
    ROUND(AVG(number_of_nights * 1.0), 3) AS avg_stay_duration
FROM hotel_bookings
GROUP BY hotel_id
ORDER BY hotel_id;



/*
12. Advance Booking Behavior
Find the average number of days customers book in advance
for each hotel.
*/

SELECT 
    hotel_id,
    ROUND(
        AVG(DATEDIFF(day, booking_date, stay_start_date)), 
        3
    ) AS avg_advance_booking_days
FROM hotel_bookings
GROUP BY hotel_id
ORDER BY hotel_id;
